# -*- coding: utf-8 -*-
"""Inhoud van de aparte dienstpagina's (lokale SEO)."""

DIENSTEN = [
{
 "slug": "schoonmaak-groningen", "icon": "sparkle", "kort": "Schoonmaak & dieptereiniging",
 "h1": "Schoonmaak en dieptereiniging in Groningen",
 "title": "Schoonmaakbedrijf Groningen | Dieptereiniging & desinfectie | JSTN",
 "desc": "Schoonmaakbedrijf in Groningen voor bedrijven en particulieren: reguliere schoonmaak, dieptereiniging en desinfectie met professionele apparatuur. Reactie binnen 12 uur.",
 "lead": "Reguliere schoonmaak of een grondige dieptereiniging van uw kantoor, praktijk, woning of (zorg)appartement. Wij werken met professionele apparatuur en hoogwaardige reinigings- en desinfectiemiddelen.",
 "pts": ["Zakelijk én particulier", "Eenmalig of periodiek", "Ook na verhuizing, ontruiming of verbouwing"],
 "blokken": [
  ("office", "Zakelijke schoonmaak", "Voor kantoren, scholen, praktijken, bedrijfspanden en zorginstellingen. Periodiek onderhoud of een eenmalige grote beurt — met vaste aanspreekpunten en duidelijke afspraken over wat er wanneer gebeurt."),
  ("home", "Woning schoonmaken", "Een woning die na een verhuizing, ontruiming of lange bewoning weer fris moet worden. Wij ontvetten, verwijderen kalk en aanslag en ontsmetten waar nodig, zodat u op een schone basis begint."),
  ("key", "Zorg-appartementen", "Snelle schoonmaak van zorgappartementen bij wisseling van cliënt, als onderdeel van een complete oplevering binnen maximaal 3 werkdagen."),
  ("drop", "Desinfectie", "Specialistische reiniging en desinfectie voor ruimtes waar hygiëne extra belangrijk is, met professionele middelen en apparatuur."),
 ],
 "faq": [
  ("Doen jullie ook eenmalige schoonmaak?", "Ja. U kunt ons inschakelen voor een eenmalige dieptereiniging, bijvoorbeeld na een verhuizing of verbouwing, of voor periodiek schoonmaakonderhoud."),
  ("Wat kost een dieptereiniging?", "Dat hangt af van de grootte van de ruimte, de staat waarin deze verkeert en wat er precies moet gebeuren. Stuur ons een korte omschrijving (eventueel met foto's) via WhatsApp of het contactformulier, dan ontvangt u binnen 12 uur een reactie."),
  ("Kunnen jullie schoonmaken in combinatie met andere klussen?", "Zeker. Omdat wij ook ontruimen, schilderen en opleveren, kunnen we alles in één keer regelen. U heeft dan één aanspreekpunt in plaats van meerdere partijen."),
  ("Doen jullie ook schoonmaak bij een bouwoplevering?", "Ja. Na een (ver)bouw maken wij het complete pand schoon voor de oplevering, inclusief glasbewassing van ramen en glazen wanden. Zo kan het pand netjes en direct bruikbaar worden opgeleverd."),
  ("Werken jullie ook buiten Groningen-stad?", "Ja, wij werken in de stad Groningen en in de omgeving, tot ongeveer 50 kilometer rondom de stad."),
 ],
 "verwant": ["vloerreiniging-groningen", "glazenwasser-groningen", "woning-opleveren-groningen"],
},
{
 "slug": "vloerreiniging-groningen", "icon": "floor", "kort": "Vloerreiniging",
 "h1": "Vloerreiniging in Groningen",
 "title": "Vloerreiniging Groningen | Scholen, kantoren & bedrijfspanden | JSTN",
 "desc": "Professionele vloerreiniging in Groningen voor scholen, kantoren en bedrijfspanden. Eenmalige dieptereiniging of periodiek onderhoud, ook in (school)vakanties.",
 "lead": "Grote vloeroppervlakken in scholen, kantoren, bedrijfspanden en andere grote ruimtes reinigen wij grondig met professionele apparatuur — voor een frisse, hygiënische en representatieve uitstraling.",
 "pts": ["Ook in (school)vakanties", "Eenmalig of periodiek onderhoud", "Professionele apparatuur"],
 "blokken": [
  ("office", "Scholen en kantoren", "Gangen, lokalen, kantine en kantoortuinen. Wij plannen de reiniging op momenten dat het gebouw leeg is, zodat leerlingen en medewerkers er geen last van hebben."),
  ("box", "Bedrijfspanden en hallen", "Grote vloeroppervlakken waar dagelijks veel wordt gelopen. Een grondige beurt verwijdert vuil dat met gewoon dweilen blijft zitten."),
  ("sparkle", "Dieptereiniging", "Een eenmalige grote beurt, bijvoorbeeld voor de start van het schooljaar, na een verbouwing of voor een oplevering."),
  ("clip", "Periodiek onderhoud", "Een vast schema zodat uw vloeren het hele jaar netjes blijven en langer meegaan."),
 ],
 "faq": [
  ("Kan vloerreiniging in de schoolvakantie?", "Ja, juist dan. Wij zijn flexibel in te plannen, ook in (school)vakanties en buiten kantoortijden, zodat uw organisatie er zo min mogelijk van merkt."),
  ("Welke vloeren reinigen jullie?", "Wij reinigen vooral grote harde vloeroppervlakken in scholen, kantoren en bedrijfspanden. Vertel ons welk type vloer u heeft, dan stemmen we de aanpak daarop af."),
  ("Wat kost vloerreiniging?", "Dat hangt af van het aantal vierkante meters, het type vloer en hoe vaak u het wilt laten doen. Vraag vrijblijvend een offerte aan; u krijgt binnen 12 uur een reactie."),
 ],
 "verwant": ["schoonmaak-groningen", "glazenwasser-groningen", "hogedrukreiniging-groningen"],
},
{
 "slug": "glazenwasser-groningen", "icon": "window", "kort": "Glasbewassing",
 "h1": "Glazenwasser in Groningen",
 "title": "Glazenwasser Groningen | Glasbewassing woning & bedrijf | JSTN",
 "desc": "Glasbewassing in Groningen voor woningen, kantoren en bedrijfspanden. Streeploos schone ramen, eenmalig of periodiek en goed te combineren met schoonmaak.",
 "lead": "Streeploos schone ramen voor woningen, kantoren en bedrijfspanden — eenmalig of periodiek, en goed te combineren met de schoonmaak van uw pand.",
 "pts": ["Woningen en bedrijfspanden", "Eenmalig of periodiek", "Te combineren met schoonmaak"],
 "blokken": [
  ("office", "Zakelijke glasbewassing", "Schone ramen bepalen voor een groot deel de eerste indruk van uw pand. Wij houden ze schoon volgens een vast schema dat bij u past."),
  ("home", "Ramen van uw woning", "Binnen en buiten, bijvoorbeeld voor de verkoop of oplevering van uw huis of gewoon voor een frisse start."),
  ("sparkle", "Gecombineerd met schoonmaak", "Laat de ramen meenemen bij een dieptereiniging of oplevering, dan is alles in één keer klaar."),
 ],
 "faq": [
  ("Wassen jullie ook ramen bij particulieren?", "Ja, wij wassen ramen voor zowel particulieren als bedrijven."),
  ("Kan glasbewassing periodiek?", "Ja, we kunnen een vast schema afspreken, bijvoorbeeld per maand of per kwartaal. Eenmalig kan natuurlijk ook."),
  ("Hoe vraag ik een prijs aan?", "Stuur ons via WhatsApp of het contactformulier het adres en een indicatie van het aantal ramen, dan reageren we binnen 12 uur."),
 ],
 "verwant": ["schoonmaak-groningen", "hogedrukreiniging-groningen", "vloerreiniging-groningen"],
},
{
 "slug": "woningontruiming-groningen", "icon": "box", "kort": "Woningontruiming",
 "h1": "Woningontruiming in Groningen",
 "title": "Woningontruiming Groningen | Huis leegruimen & ontruimen | JSTN",
 "desc": "Woningontruiming in Groningen: wij ruimen woning, schuur, berging en tuin volledig leeg, voeren alles netjes af en kunnen de woning bezemschoon of verkoopklaar opleveren.",
 "lead": "Moet uw woning, of de woning van uw ouders, worden leeggeruimd? Wij verwijderen de volledige inboedel uit woning, schuur, berging en tuin en zorgen dat alles netjes wordt afgevoerd.",
 "pts": ["Ook spoedontruimingen", "Bruikbare spullen krijgen een tweede leven", "Bezemschoon of verkoopklaar opgeleverd"],
 "blokken": [
  ("home", "Particuliere ontruiming", "Na een overlijden, een verhuizing naar een zorginstelling of de verkoop van een huis. Wij werken zorgvuldig en met respect voor de situatie en de spullen."),
  ("office", "Ontruiming voor verhuurders en corporaties", "Bij gedwongen of ongedwongen beëindiging van de huur verzorgen wij de ontruiming van uw vastgoed, snel en zorgvuldig."),
  ("drop", "Duurzaam afvoeren", "Waar mogelijk hergebruiken we materialen en inventaris en scheiden we het afval zorgvuldig."),
  ("roller", "Daarna direct opknappen", "Omdat wij ook schoonmaken, schilderen en opleveren, kan de woning na de ontruiming direct klaargemaakt worden voor verkoop of verhuur."),
 ],
 "faq": [
  ("Hoe snel kunnen jullie een woning ontruimen?", "Dat hangt af van de omvang en onze planning, maar we zijn flexibel inzetbaar, ook voor spoedontruimingen. Neem contact op, dan kijken we samen wat mogelijk is."),
  ("Wat gebeurt er met de spullen uit de woning?", "Bruikbare spullen geven we waar mogelijk een tweede leven. De rest voeren we netjes en gescheiden af."),
  ("Kan de woning daarna ook opgeleverd worden?", "Ja. Wij kunnen de woning bezemschoon opleveren aan een woningcorporatie of verhuurder, of volledig verkoopklaar maken."),
  ("Hoe bepalen jullie de prijs van een ontruiming?", "Op basis van de grootte van de woning, de hoeveelheid inboedel en wat er na de ontruiming nog moet gebeuren. Vooraf spreken we duidelijk af wat er gebeurt; indien gewenst kunnen we een vaste prijs afspreken."),
 ],
 "verwant": ["woning-opleveren-groningen", "verhuizen-groningen", "schoonmaak-groningen"],
 "blog": "zo-kies-je-een-bedrijf-voor-woningontruiming-in-groningen",
},
{
 "slug": "verhuizen-groningen", "icon": "truck", "kort": "Verhuizen voor senioren",
 "h1": "Verhuizen in Groningen, met extra aandacht voor senioren",
 "title": "Verhuizen Groningen | Seniorenverhuizing, in- en uitpakken | JSTN",
 "desc": "Verhuisservice in Groningen voor particulieren en senioren: inpakken, verhuizen, uitpakken, kasten inrichten en schilderijen ophangen. Verhuisdozen beschikbaar.",
 "lead": "Een verhuizing is een grote stap. Wij zorgen dat alles zo soepel mogelijk verloopt, met extra aandacht voor senioren en hun persoonlijke bezittingen.",
 "pts": ["Inpakken én uitpakken", "Verhuisdozen en inpakmateriaal beschikbaar", "Ook op korte termijn"],
 "blokken": [
  ("box", "Inpakken", "Wij pakken uw spullen zorgvuldig in. Verhuisdozen en inpakmateriaal stellen wij beschikbaar."),
  ("truck", "Verhuizen", "Meubels en spullen veilig naar uw nieuwe woning, ook naar een seniorenwoning of zorginstelling."),
  ("home", "Uitpakken en inrichten", "We richten uw kasten weer in, hangen schilderijen en klokken op en sluiten indien gewenst uw apparatuur weer aan. Zo voelt u zich snel weer thuis."),
  ("clip", "Oude woning opleveren", "Ook de oude woning kunnen wij leegruimen, schoonmaken en opleveren aan de verhuurder of corporatie."),
 ],
 "faq": [
  ("Helpen jullie ook senioren met verhuizen?", "Ja, daar zijn we in gespecialiseerd. We nemen de tijd, gaan zorgvuldig om met persoonlijke bezittingen en richten de nieuwe woning zo in dat het direct vertrouwd voelt."),
  ("Pakken jullie ook in en uit?", "Ja. Van inpakken tot uitpakken, kasten inrichten en schilderijen ophangen: wij nemen het werk volledig uit handen."),
  ("Kan een verhuizing op korte termijn?", "Ook als u op korte termijn hulp nodig heeft, denken we graag mee. Neem contact op, dan kijken we wat er in de planning past."),
  ("Kunnen jullie ook de oude woning opleveren?", "Ja, we kunnen de oude woning leegruimen, schoonmaken en opleveren volgens de voorwaarden van uw verhuurder of corporatie."),
 ],
 "verwant": ["woningontruiming-groningen", "woning-opleveren-groningen", "schilder-groningen"],
},
{
 "slug": "woning-opleveren-groningen", "icon": "clip", "kort": "Woning opleveren",
 "h1": "Huurwoning opleveren in Groningen",
 "title": "Huurwoning opleveren Groningen | Opleveringsschoonmaak | JSTN",
 "desc": "Uw huurwoning opleveren in Groningen aan corporatie, verhuurder of zorginstelling: vloeren, gordijnen en lampen verwijderen, tuin opruimen, schoonmaken en bezemschoon opleveren.",
 "lead": "Moet uw woning worden opgeleverd aan een woningcorporatie, verhuurder of zorginstelling? Wij zorgen dat de woning netjes en volgens de opleveringsvoorwaarden wordt achtergelaten.",
 "pts": ["Volgens de opleveringsvoorwaarden", "Vaste prijs mogelijk", "Van begin tot eind geregeld"],
 "blokken": [
  ("box", "Leeghalen", "Verwijderen van vloerafwerking, gordijnen, lampen en achtergebleven spullen, en het opruimen van de tuin."),
  ("sparkle", "Opleveringsschoonmaak", "Sanitair, keuken, ramen en vloeren schoon, zodat de woning bezemschoon of schoon wordt opgeleverd."),
  ("roller", "Herstel en schilderwerk", "Gaten dichten, wanden en plafonds bijwerken of opnieuw schilderen als de verhuurder dat vraagt."),
 ],
 "faq": [
  ("Wat betekent bezemschoon opleveren?", "Bij bezemschoon opleveren is de woning leeg en vrij van grof vuil. Welke eisen precies gelden, staat in uw huurcontract of de opleveringsvoorwaarden van de verhuurder. Wij stemmen ons werk daarop af."),
  ("Kunnen jullie een vaste prijs afspreken?", "Ja. Vooraf spreken we duidelijk af wat er moet gebeuren en kunnen we indien gewenst een vaste prijs aanbieden."),
  ("Wat als de verhuurder nog iets afkeurt?", "Neem direct contact met ons op. We spreken vooraf af wat er gebeurt en zorgen dat de afgesproken werkzaamheden goed worden afgerond."),
 ],
 "verwant": ["woningontruiming-groningen", "schoonmaak-groningen", "schilder-groningen"],
},
{
 "slug": "zorgappartementen-opleveren", "icon": "key", "kort": "Zorg-appartementen opleveren",
 "h1": "Zorg-appartementen opleveren binnen 3 werkdagen",
 "title": "Zorgappartementen opleveren Groningen | Binnen 3 werkdagen | JSTN",
 "desc": "Voor zorginstellingen in Groningen: bij vertrek van een bewoner leveren wij het zorgappartement binnen maximaal 3 werkdagen op — ontruimen, herstellen, schilderen en schoonmaken.",
 "lead": "Bij het vertrek van een bewoner zorgen wij dat het appartement binnen maximaal 3 werkdagen weer beschikbaar is voor een nieuwe cliënt, opgeleverd volgens het door u gewenste opleverniveau.",
 "pts": ["Binnen maximaal 3 werkdagen", "Eén partij voor het hele proces", "Op uw opleverniveau"],
 "blokken": [
  ("box", "Ontruimen", "Respectvol en zorgvuldig leeghalen van het appartement, in overleg met familie en de instelling."),
  ("roller", "Opknappen en herstellen", "De benodigde opknap- en herstelwerkzaamheden, inclusief schilder- en behangwerk."),
  ("sparkle", "Schoonmaak en desinfectie", "Grondige schoonmaak en waar nodig desinfectie, zodat het appartement hygiënisch en fris wordt opgeleverd."),
  ("clip", "Administratieve afhandeling", "Wij kunnen ook de administratieve afhandeling verzorgen, zodat u het hele proces uit handen geeft."),
 ],
 "faq": [
  ("Hoe snel is een zorgappartement weer beschikbaar?", "Wij leveren het appartement binnen maximaal 3 werkdagen op, zodat de leegstand zo kort mogelijk blijft."),
  ("Werken jullie volgens ons opleverniveau?", "Ja. Vooraf spreken we het gewenste opleverniveau met u af, en daar leveren we op."),
  ("Kunnen jullie meerdere appartementen tegelijk doen?", "Neem contact met ons op over aantallen en planning. We werken met vaste aanspreekpunten en kunnen snel schakelen."),
 ],
 "verwant": ["schoonmaak-groningen", "schilder-groningen", "woningontruiming-groningen"],
},
{
 "slug": "schilder-groningen", "icon": "roller", "kort": "Schilder- & behangwerk",
 "h1": "Schilder- en behangwerk in Groningen",
 "title": "Schilder Groningen | Schilder- & behangwerk binnen | JSTN",
 "desc": "Schilder- en behangwerk in Groningen voor woningen en zorgappartementen: wanden en plafonds bijwerken of volledig opnieuw schilderen en behangen. Eén aanspreekpunt.",
 "lead": "Van het bijwerken van wanden en plafonds tot het volledig opnieuw schilderen of behangen van een ruimte. Netjes, vakkundig en met oog voor een strak eindresultaat.",
 "pts": ["Woningen en zorgappartementen", "Strak en netjes afgewerkt", "Eén vast aanspreekpunt"],
 "blokken": [
  ("home", "Uw nieuwe woning opknappen", "Verhuist u naar een woning die een opknapbeurt kan gebruiken? Wij maken er snel een fijne, persoonlijke plek van."),
  ("roller", "Schilderen en behangen", "Wanden, plafonds, kozijnen en deuren — bijwerken of volledig opnieuw."),
  ("clip", "Meer werk in één keer", "Wij kunnen ook vloeren laten leveren en leggen, gordijnen ophangen en aanpassingen in keuken of badkamer coördineren."),
  ("key", "Voor verhuurders en zorginstellingen", "Schilderwerk als onderdeel van een snelle oplevering bij wisseling van huurder of cliënt."),
 ],
 "faq": [
  ("Doen jullie ook behangwerk?", "Ja, wij verzorgen zowel schilder- als behangwerk."),
  ("Kunnen jullie ook andere klussen regelen?", "Ja. Naast schilderen en behangen kunnen we bijvoorbeeld het leveren en leggen van vloeren, het ophangen van gordijnen en aanpassingen in keuken of badkamer voor u regelen en coördineren."),
  ("Hoe vraag ik een offerte aan?", "Stuur ons een omschrijving en eventueel foto's van de ruimtes via WhatsApp of het contactformulier. U krijgt binnen 12 uur een reactie."),
 ],
 "verwant": ["verhuizen-groningen", "woning-opleveren-groningen", "zorgappartementen-opleveren"],
},
{
 "slug": "hogedrukreiniging-groningen", "icon": "drop", "kort": "Hogedrukreiniging",
 "h1": "Hogedrukreiniging in Groningen",
 "title": "Hogedrukreiniging Groningen | Oprit, terras, dak & gevel | JSTN",
 "desc": "Hogedrukreiniging in Groningen voor opritten, terrassen, daken, gevels en bedrijfsterreinen. Mos en aanslag weg, voegen opnieuw ingevuld. Particulier en zakelijk.",
 "lead": "Een oprit vol mos, een glad tuinpad of een dak met aanslag — met hogedruk maken wij het weer schoon en veilig. Voor particulieren en bedrijven.",
 "pts": ["Opritten, terrassen, daken en gevels", "Voegen opnieuw gevuld", "Eenmalig of als onderhoud"],
 "blokken": [
  ("home", "Oprit en terras", "Mos, algen en aanslag verwijderd. Daarna vullen we de voegen opnieuw met voegzand, zodat onkruid minder snel terugkomt."),
  ("office", "Bedrijfsterreinen", "Mos en aanslag op terreinen, vluchtroutes en looppaden zijn een veiligheidsrisico. Wij houden ze schoon en veilig."),
  ("box", "Daken en gevels", "Reiniging van daken en gevels, zodat uw pand er weer verzorgd en representatief uitziet."),
 ],
 "faq": [
  ("Vullen jullie de voegen ook opnieuw?", "Ja. Na het reinigen van uw bestrating vullen we de voegen opnieuw met voegzand, zodat onkruid minder snel terugkomt."),
  ("Is hogedrukreiniging ook voor bedrijven?", "Ja. Juist op platte daken, vluchtroutes en looppaden is mos en aanslag een risico op uitglijden. Een vast onderhoudsschema helpt om dat te voorkomen."),
  ("Wat kost hogedrukreiniging?", "Dat hangt af van het oppervlak en het soort ondergrond. Stuur ons een foto en een indicatie van de vierkante meters, dan reageren we binnen 12 uur."),
 ],
 "verwant": ["glazenwasser-groningen", "schoonmaak-groningen", "vloerreiniging-groningen"],
},
]

PLAATSEN = ["Groningen", "Haren", "Hoogezand", "Ten Boer", "Bedum", "Winsum", "Zuidhorn", "Leek", "Roden",
            "Eelde", "Zuidlaren", "Assen", "Veendam", "Appingedam", "Delfzijl", "Winschoten", "Stadskanaal",
            "Uithuizen", "Drachten"]

KAART = {
 "schoonmaak-groningen": "Reguliere schoonmaak en grondige dieptereiniging met professionele apparatuur.",
 "vloerreiniging-groningen": "Grote vloeren in scholen, kantoren en bedrijfspanden grondig schoon.",
 "glazenwasser-groningen": "Streeploos schone ramen voor woningen en bedrijfspanden.",
 "woningontruiming-groningen": "Woning, schuur en tuin leeggeruimd — ook spoedontruimingen.",
 "verhuizen-groningen": "Inpakken, verhuizen en uitpakken, met extra aandacht voor senioren.",
 "woning-opleveren-groningen": "Uw huurwoning netjes opgeleverd volgens de voorwaarden.",
 "zorgappartementen-opleveren": "Binnen maximaal 3 werkdagen klaar voor een nieuwe cliënt.",
 "schilder-groningen": "Strak schilder- en behangwerk, netjes en vakkundig uitgevoerd.",
 "hogedrukreiniging-groningen": "Opritten, terrassen, daken en gevels weer schoon en veilig.",
}
